# Path to the blast executables.
# 
# Sequence Server scans the given directory for blast binaries. Ideally it
# should point the `bin` of your BLAST+ installation. Not setting this
# value, or setting it to `nil` will default to searching the system `PATH`.
#
# Uncomment the following line, and change to appropriate value to use.
#
# bin: ~/ncbi-blast-2.2.25+/bin/

# Path to blast database.
#
# Sequence Server scans the given directory (including the sub-directories)
# for blast database. You can not specify more than one top-level directory.
# Not setting this value, will default to searching `database` directory
# relative to the current working directory.
#
# Uncomment the following line, and change to appropriate value to use.
#
# database: ~/blast_databases/

# Port to run Sequence Server on.
#
# The app will then be accessible at http://your-ip:port. Defaults to 4567.
# http://localhost:port is also valid for local access.
#
# Uncomment the following line, and change to appropriate value to use.
#
# port: 4567

# number of threads to be use when blasting
#
# This option is passed directly to BLAST+. Setting this option to more
# than 1 may crash BLAST+ if it was not compiled with threading support.
# Default is to use the safe value of 1.
#
# Uncomment the following line, and change to appropriate value to use.
#
# num_threads: 1
